name: Build

on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]

jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        logic: [1,2]
    steps:
    - uses: actions/checkout@v6
    - name: Configure
      run: cmake -B build -A x64 -DLOGIC=${{ matrix.logic }}

    - name: Build
      run: cmake --build build --config Release

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: windows-${{ matrix.logic }}
        path: build/Analyzers/Release/*.dll

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            logic: 1
          - arch: x86_64
            logic: 2
          - arch: arm64
            logic: 2

    steps:
    - uses: actions/checkout@v6

    - name: Configure
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DLOGIC=${{ matrix.logic }}

    - name: Build
      run: cmake --build build

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: macos-${{ matrix.arch }}-${{ matrix.logic }}
        path: build/Analyzers/*.so

  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        logic: [1,2]

    steps:
    - uses: actions/checkout@v6

    - name: Install gcc-9 and patchelf (Logic 1 only)
      if: matrix.logic == 1
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-9 g++-9 patchelf

    - name: Configure (Logic 1)
      if: matrix.logic == 1
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DLOGIC=1 \
          -DCMAKE_C_COMPILER=gcc-9 \
          -DCMAKE_CXX_COMPILER=g++-9

    - name: Configure (Logic 2)
      if: matrix.logic == 2
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DLOGIC=2


    - name: Build
      run: cmake --build build

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: linux-${{ matrix.logic }}
        path: build/Analyzers/*.so

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [windows, macos, linux]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
