name: Build

on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        logic: [1,2]
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -B build -A x64 -DLOGIC=${{ matrix.logic }}

    - name: Build
      run: cmake --build build --config Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.logic }}
        path: build/Analyzers/Release/*.dll

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        logic: [1,2]

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DLOGIC=${{ matrix.logic }}

    - name: Build
      run: cmake --build build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}-${{ matrix.logic }}
        path: build/Analyzers/*.so

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        logic: [1,2]

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DLOGIC=${{ matrix.logic }}

    - name: Build
      run: cmake --build build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.logic }}
        path: build/Analyzers/*.so

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [windows, macos, linux]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}